### ISSUE TITLE
Ask About the Dataset of PromptTTS++

### ISSUE THREAD

**Issue by Levent9** [reppy4620/diffusion#1]
Hello! I recently came across your insightful paper PROMPTTTS++, I was wondering if you have any plans to open source the dataset used in your study.

**Comment by reppy4620** [comment]
Sorry for late reply. 
PromptTTS++ is a project I worked on during my internship. I believe it is planned to be released publicly, but the timing of its release depends on the company, and I am not sure when that will be.
